name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Lint with ruff
        uses: greenbone/actions/lint-python@v3
        with:
          packages: mdit_py_toc tests
          python-version: ${{ matrix.python-version }}
          linter: ruff

  test:
    name: Run all tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: poetry run python -m unittest -v

  mypy:
    name: Check type hints
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Run mypy
        uses: greenbone/actions/mypy-python@v3
        with:
          python-version: ${{ matrix.python-version }}

  check-version:
    name: Check versioning for consistency
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
      - name: Check version
        run: |
          poetry run pontos-version verify current
